=head1 NAME

[TODO]


=head1 OVERVIEW

[TODO]

=head1 AUTHORS

Nosoff Alex, C<plcgi1@gmail.com>

Please report any errors, issues or suggestions to the author.  The
most recent version of the WOA Tutorial can be found at
L<https://github.com/plcgi1/woa-toolkit-core/lib/WOA/Manual/*>.

Copyright 2006-2011, Nosoff Alex, under Creative Commons License
(L<http://creativecommons.org/licenses/by-sa/3.0/us/>).
