=pod

=head1 NAME

WOA::FAQ - Frequently Asked Questions for WOA,WOAx toolkit

=head1 DESCRIPTION

Though L<WOA> itself has a general FAQ section in the
pod, it's more for advocacy. Here's an incomplete and growing list of
the actual questions I have been frequently asked (or found on the
net) about L<WOA>.

=head2 [TODO]

[TODO]


=head1 GIT repository

=begin html

<a href="https://github.com/plcgi1/woa-toolkit-core">https://github.com/plcgi1/woa-toolkit-core</a>

=end html


=head1 AUTHOR

Nosoff Alex, C<plcgi1@gmail.com>

=head1 COPYRIGHT

Copyright 2006-2010, Nosoff Alex, under Creative Commons License
(L<http://creativecommons.org/licenses/by-sa/3.0/us/>).

=cut
